### ISSUE TITLE
Build fails (fedora 37)

### ISSUE THREAD

**Issue by ex-nerd** [BitBangingBytes/gr-smart_meters#38]
I'm following the instructions at https://wiki.recessim.com/view/Gr-smart_meters_Setup_Guide and getting a weird error when trying to run `cmake` on `gr-smart_meters` (branch adjusted from those instructions to use `maint-3.10`). 

Output looks like:

```
-- Build type not specified: defaulting to release.
-- Using GMP.
-- User set python executable /usr/bin/python3
-- Extracting version information from git describe...
fatal: No names found, cannot describe anything.
-- Found pybind11: /usr/include (found version "2.10.3")
-- Using install prefix: /usr/local
-- Building for version: g36ea098 / 1.0.0git
-- No C++ unit tests... skipping
-- PYTHON and GRC components are enabled
-- Python checking for pygccxml - found
CMake Error at /lib64/cmake/gnuradio/GrPybind.cmake:220 (message):
  Python bindings for Deframer.h are out of sync
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:35 (GR_PYBIND_MAKE_OOT)
```

gnuradio package versions are `gnuradio-3.10.3.0-4.fc37.x86_64` and `python3-gnuradio-3.10.3.0-4.fc37.x86_64` which is reported as a compatible version.

I set `BINDTOOL_GEN_AUTOMATIC(1)` in `Deframer_python.cc` and `cmake` completed successfully, however `make` still fails with the following output:

```
[  0%] Built target pygen_apps_9a6dd
[ 18%] Built target pygen_python_40be2
[ 27%] /home/USERNAME/gas_meter/FHSS_Utils/gr-smart_meters/python/bindings/../../include/smart_meters/Deframer.h
[ 54%] Built target gnuradio-smart_meters
[ 63%] Built target smart_meters_docstrings
In file included from <built-in>:437:
<command line>:3:9: error: macro name must be an identifier
#define -U__PIE__ 1
        ^
1 error generated.
Traceback (most recent call last):
  File "/home/USERNAME/gas_meter/FHSS_Utils/gr-smart_meters/python/bindings/bind_oot_file.py", line 57, in <module>
    bg.gen_file_binding(args.filename)
  File "/usr/lib64/python3.11/site-packages/gnuradio/bindtool/core/generator.py", line 211, in gen_file_binding
    raise(e)
  File "/usr/lib64/python3.11/site-packages/gnuradio/bindtool/core/generator.py", line 198, in gen_file_binding
    header_info = parser.get_header_info(self.namespace)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/gnuradio/blocktool/core/parseheader_generic.py", line 324, in get_header_info
    decls = parser.parse(
            ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/__init__.py", line 51, in parse
    declarations = parser.read_files(files, compilation_mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/project_reader.py", line 255, in read_files
    return self.__parse_all_at_once(files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/project_reader.py", line 356, in __parse_all_at_once
    return self.read_string(''.join(header_content))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/project_reader.py", line 369, in read_string
    decls = reader.read_string(content)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/source_reader.py", line 377, in read_string
    decls = self.read_file(header_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/source_reader.py", line 303, in read_file
    return self.read_cpp_source_file(source_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/source_reader.py", line 322, in read_cpp_source_file
    xml_file = self.create_xml_file(ffname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pygccxml/parser/source_reader.py", line 263, in create_xml_file
    raise RuntimeError(
RuntimeError: Error occurred while running CASTXML xml file does not exist
make[2]: *** [python/bindings/CMakeFiles/Deframer_python.cc_regen_bindings.dir/build.make:73: /home/USERNAME/gas_meter/FHSS_Utils/gr-smart_meters/python/bindings}/Deframer_python.cc] Error 1
make[1]: *** [CMakeFiles/Makefile2:314: python/bindings/CMakeFiles/Deframer_python.cc_regen_bindings.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by morelint** [comment]
Got received the same behavior on Ubuntu 22.04
Not sure, that this solution is correct, but after modifying \gr-smart_meters-maint-3.10\python\bindings\CMakeLists.txt
```
list(APPEND smart_meters_python_files
    GridStream_python.cc python_bindings.cc)
```
i was able to compile the project without error.

**Comment by ex-nerd** [comment]
I can confirm this also fixes the build for me, however gnuradio is giving me errors saying `libgnuradio-fhss_utils` isn't found, so I still have some other (possibly unrelated) issues to track down.

**Comment by cribdragg3r** [comment]
> Got received the same behavior on Ubuntu 22.04 Not sure, that this solution is correct, but after modifying \gr-smart_meters-maint-3.10\python\bindings\CMakeLists.txt
> 
> ```
> list(APPEND smart_meters_python_files
>     GridStream_python.cc python_bindings.cc)
> ```
> 
> i was able to compile the project without error.

This also fixed it for me.

**Comment by ex-nerd** [comment]
Got the library changes figured out (apparently I never set my env up for `/usr/local` path variants):

```
export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/usr/local/lib64/python3.11/site-packages:$PYTHONPATH
```

But now trying to run the rtl-sdr example gives me:

```
Executing: /usr/bin/python3 -u /home/[REDACTED]/FHSS_Utils/gr-smart_meters/examples/GridStream_RTL_SDR.py

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
log :warning: Matplotlib is a required dependency to use DistanceRadar and AzElPlot.  Please install matplotlib to use these blocks (https://matplotlib.org/)
Traceback (most recent call last):
  File "/home/[REDACTED]/FHSS_Utils/gr-smart_meters/examples/GridStream_RTL_SDR.py", line 42, in <module>
    import smart_meters
  File "/usr/local/lib64/python3.11/site-packages/smart_meters/__init__.py", line 18, in <module>
    from .smart_meters_python import *
ImportError: /usr/local/lib64/python3.11/site-packages/smart_meters/smart_meters_python.cpython-311-x86_64-linux-gnu.so: undefined symbol: _Z13bind_DeframerRN8pybind117module_E
```

(odd warning because `matplotlib` is installed, but I think that's unrelated)

**Comment by BitBangingBytes** [comment]
The original issue with python bindings has been fixed
